### PR TITLE
incorporate cluster label fix

### PR DESCRIPTION
**Pull request by pintohutch**

### CODE REVIEW

**Comment by pintohutch** [comment]
friendly ping here @bwplotka @TheSpiritXIII :)

**Review by bwplotka — COMMENTED** [review]
Thanks!

This incorporates export changes to 2.35 but also updates 5 irrelevant go modules. Ideally we don't so this commit is self-contained (I doubt export module upgrade requires those).

I would recommend changing go.mod of github.com/GoogleCloudPlatform/prometheus-engine manually to v0.6.4-rc.0 and doing `go mod tidy`. This will pull what's needed but not touch any other dep.

**Comment by pintohutch** [comment]
I think this is happening because the `release-0.6` branch also includes [changes](https://github.com/GoogleCloudPlatform/prometheus-engine/commit/46b559329d53c98d50d861e538b70c1d5e1850a7) to the underlying k8s library.

Lemme open up a release branch just for `release-0.6.2` to minimize the net changes.

**Review by bwplotka — APPROVED** [review]
Thanks!

**Pull request merged**
