### PR TITLE
Update exp package

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Cherrypicked https://github.com/prometheus/prometheus/pull/12650 since I was running into https://github.com/prometheus/prometheus/issues/12649 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24881 when upgrading the OTel collector.

Original author:    Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by pintohutch** [comment]
LGTM

**Review by pintohutch — APPROVED** [review]
Note - this is available in Prometheus OSS 2.48. We're still not close to that yet in our fork, so I think the dedicated patch makes sense.

**Comment by ridwanmsharif** [comment]
I don't have merge access on the repo, @pintohutch do you mind hitting the big green button too?

**Review by bwplotka — APPROVED** [review]
Thanks!

**Pull request merged**
