### PR TITLE
chore: enable boring crypto

### PR DESCRIPTION
**Pull request by bernot-dev**
Enable boring crypto flag for builds of our fork.

### CODE REVIEW

**Comment by pintohutch** [comment]
LGTM - can you create PRs against [2.43](https://github.com/GoogleCloudPlatform/prometheus/tree/release-2.43.1-gmp) and [2.45](https://github.com/GoogleCloudPlatform/prometheus/tree/release-2.45.3-gmp)?

**Comment by pintohutch** [comment]
Actually @bernot-dev can you kick-off a prombench too?

**Review by TheSpiritXIII — APPROVED** [review]

**Comment by bernot-dev** [comment]
@pintohutch I don't see anything concerning in the Prombench results. If anything, the boringcrypto version performs very slightly better on some of the benchmarks, but I assume it's within the margin for error.

**Comment by pintohutch** [comment]
Awesome - thanks for checking

**Review by pintohutch — APPROVED** [review]
:shipit:

**Pull request merged**
